project_id = "mdrcbaaxuryptxockxjj"

[functions.migrate-users]
verify_jwt = false

[functions.restore-wallets]
verify_jwt = false

[functions.restore-all-data]
verify_jwt = false

[functions.update-app-config]
verify_jwt = false