-- Add columns for tracking affiliate activity and inactivity notifications
ALTER TABLE public.affiliates 
ADD COLUMN IF NOT EXISTS last_revenue_at timestamptz,
ADD COLUMN IF NOT EXISTS last_inactivity_notification text;

-- Add comment for documentation
COMMENT ON COLUMN public.affiliates.last_revenue_at IS 'Timestamp of the last commission generated by this affiliate';
COMMENT ON COLUMN public.affiliates.last_inactivity_notification IS 'Type of the last inactivity notification sent (30_days, 45_days, 60_days_deactivated)';